<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\SecretVault;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('vault_secret_create')]
#[Description(<<<'MARKDOWN'
    Create a vault slot for a secret that will be pasted in a browser

    Mints a one-use-per-secret paste slot. Returns `ref` (`vault:<id>`, pass it where the secret would go -- e.g. the `git_token` field of project_create or source_inspect) and `url` (the form the customer opens and pastes the secret into). The entry is reusable until it expires (`expires_in` seconds), then gone; a paste can be repeated while it lives. **The secret never passes through the API caller** -- that is this mechanism's whole purpose, for agents that must not relay a private-repository token through a conversation.

    Calls POST /api/vault/secrets. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class VaultSecretCreateTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/vault/secrets';
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'type',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'type' => $schema->string()->description('The request field the reference will be passed in (e.g. `git_token`, `env_vars`). Free-form snake_case -- the field the caller will send `vault:<ref>` in. The paste form shows help from `resources/vault/<type>.md` when that file exists, else the default help. Example: git_token.')->required(),
        ];
    }
}
