<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Containers;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('app_health_check')]
#[Description(<<<'MARKDOWN'
    Check that the deployed application answers on its published ports

    Probes each port the application publishes from inside the account container, over loopback. Does not go through the domain, DNS, TLS or the reverse proxy, so a failure here means the application itself is not answering. `healthy` is null when the application publishes no port to probe. `checks` answers a different question from `healthy`: not whether something answered, but whether what answered is the application - a project the engine could not recognise is served the engine's own placeholder page with a 200, and a static site that has lost its front page answers 404 on `/` while every other page works. Each check names a stable id, the group it came from, and where it can be said, what to do about it. `serving` is the one-word summary: `ok`, or what is being served instead.

    Calls GET /api/projects/{username}/app/health.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class AppHealthCheckTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/app/health';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'timeout',
            'attempts',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'timeout' => $schema->integer(),
            'attempts' => $schema->integer(),
        ];
    }
}
