/opt/panelalpha/shared-hosting/users/*/log/apache2/*.log
{
    monthly
    rotate 100
    dateext
    dateformat -%Y-%m
    extension .log
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
        for user_dir in /opt/panelalpha/shared-hosting/users/*; do
            compose_file="$user_dir/docker-compose.yml"
            [ -f "$compose_file" ] || continue
            docker compose -f "$compose_file" exec php apachectl graceful >/dev/null 2>&1 || true
        done
    endscript
}
