/opt/panelalpha/shared-hosting/logs/modsecurity/audit.log
{
    daily
    size 100M
    rotate 30
    create
    dateext
    dateformat -%Y-%m-%d-%H-%M-%S
    extension .log
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
        bash /opt/panelalpha/shared-hosting/scripts/post-modsec-audit-log-rotate.sh || true
    endscript
}