/opt/panelalpha/shared-hosting/webserver-logs/nginx-proxy/*/*.log
{
    monthly
    rotate 100
    dateext
    dateformat -%Y-%m
    extension .log
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
        docker compose -f /opt/panelalpha/shared-hosting/docker-compose.yml exec webserver bash -c 'kill -SIGUSR1 $(cat /var/run/nginx.pid)'
    endscript
}
