<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Projects;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('project_rebuild')]
#[Description(<<<'MARKDOWN'
    Rebuild user environment

    Calls POST /api/projects/{username}/rebuild. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class ProjectRebuildTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/rebuild';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'env_vars',
            'zip_path',
            'recipe',
            'stages',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'env_vars' => $schema->object()->description('KEY=value overrides, merged onto the ones the project already carries — send only what changes. An empty value removes that key; null clears them all.'),
            'zip_path' => $schema->string()->description('Optional archive under the user home to import into ~/project before detect/apply'),
            'recipe' => $schema->string()->description('Deploy with this recipe instead of the one detection picks. Takes an id from `application.candidates` on POST /source/inspect, and inspecting with the same id previews exactly what this deploys. An id this engine does not ship fails the deploy rather than falling back to detection. Applies to this deploy only - nothing is stored, so the next deploy without it detects again. Example: php.'),
            'stages' => $schema->object()->description('Commands this deploy runs, per stage. A stage named here replaces that stage entirely; a stage left out keeps the platform defaults; a stage given as [] runs nothing. Applies to this deploy only - nothing is stored.'),
        ];
    }
}
