#!/usr/bin/env node
/**
 * PanelAlpha CLI helper for n8n.
 * Runs inside the `n8n` container — all dependencies are already present.
 *
 * Auth bootstrap (no stored credentials):
 *   1. Read encryptionKey from /home/node/.n8n/config (auto-generated by n8n on first boot)
 *   2. Derive JWT signing secret from the settings table (key='signing.jwt') — or fall back to
 *      sha256(every-other-char-of-encryptionKey) which is exactly what n8n's JwtService does
 *   3. Read owner user from SQLite → compute JWT hash → sign token → use as n8n-auth cookie
 */

import { createHash, createHmac } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { DatabaseSync } from 'node:sqlite';

// bcryptjs is the only external dep — it is bundled with n8n for password hashing
const require = createRequire('/usr/local/lib/node_modules/n8n/package.json');
const bcryptjs = require('bcryptjs');

// ---------------------------------------------------------------------------
// SQLite helper — node:sqlite is built into Node.js v22+ (no native bindings)
// ---------------------------------------------------------------------------

let _db;
function db() {
  if (!_db) _db = new DatabaseSync('/home/node/.n8n/database.sqlite');
  return _db;
}

// ---------------------------------------------------------------------------
// Auth bootstrap
// ---------------------------------------------------------------------------

function getEncryptionKey() {
  try {
    const config = JSON.parse(readFileSync('/home/node/.n8n/config', 'utf8'));
    if (config.encryptionKey) return config.encryptionKey;
  } catch {}
  if (process.env.N8N_ENCRYPTION_KEY) return process.env.N8N_ENCRYPTION_KEY;
  throw new Error('Cannot find n8n encryption key — is the volume mounted and has n8n started at least once?');
}

function getJwtSecret() {
  // n8n persists the JWT secret in the settings table after first boot
  const row = db().prepare("SELECT value FROM settings WHERE key = 'signing.jwt'").get();
  if (row) return JSON.parse(row.value);

  // Fallback: derive the same way n8n's JwtService does when no persisted secret exists
  const encKey = getEncryptionKey();
  let baseKey = '';
  for (let i = 0; i < encKey.length; i += 2) baseKey += encKey[i];
  return createHash('sha256').update(baseKey).digest('hex');
}

function computeJwtHash(email, passwordDbCol) {
  // Mirrors AuthService.createJWTHash(): base64(sha256(email + ':' + bcrypt_hash)).slice(0, 10)
  return createHash('sha256').update(`${email}:${passwordDbCol}`).digest('base64').substring(0, 10);
}

function mintJwt(userId, email, passwordDbCol) {
  const secret = getJwtSecret();
  const hash = computeJwtHash(email, passwordDbCol);
  // HS256 implemented with node:crypto — no external jwt library needed
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const payload = Buffer.from(JSON.stringify({ id: userId, hash })).toString('base64url');
  const sig = createHmac('sha256', secret).update(`${header}.${payload}`).digest('base64url');
  return `${header}.${payload}.${sig}`;
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

const [,, command, ...args] = process.argv;

if (command === 'info') {
  console.log(JSON.stringify(['install', 'roles:list', 'users:list', 'users:add', 'users:delete', 'users:reset-password', 'users:sso']));
  process.exit(0);
}

if (command === 'roles:list') {
  console.log(JSON.stringify(['global:owner', 'global:admin', 'global:member']));
  process.exit(0);
}

(async () => {
  try {
    switch (command) {

      case 'install': { // <url> <title> <adminUser> <adminEmail> <adminPassword>
        const [url,, adminUser, adminEmail, adminPassword] = args;
        if (!url || !adminUser || !adminEmail || !adminPassword) {
          throw new Error('Usage: install <url> <title> <adminUser> <adminEmail> <adminPassword>');
        }

        // Wait for n8n to be ready
        for (let i = 0; i < 60; i++) {
          try {
            const r = await fetch('http://localhost:5678/healthz');
            if (r.ok) break;
          } catch {}
          await new Promise(r => setTimeout(r, 2000));
          if (i === 59) throw new Error('Timed out waiting for n8n to start');
        }

        const [firstName, ...rest] = adminUser.split(' ');
        const lastName = rest.join(' ') || '-';

        // Spoof the Host/Proto headers so n8n derives its instanceUrl and cookie
        // domain from the real public URL — same as when the browser setup wizard
        // runs through nginx. Node.js fetch allows overriding Host unlike browsers.
        const urlObj = new URL(url);
        const result = await (await fetch('http://localhost:5678/rest/owner/setup', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Host': urlObj.host,
            'X-Forwarded-Proto': urlObj.protocol.replace(':', ''),
          },
          body: JSON.stringify({ email: adminEmail, firstName, lastName, password: adminPassword }),
        })).json();

        // 400 "already setup" is fine — just get the existing owner id from SQLite
        let id = result?.data?.id ?? result?.id;
        if (!id) {
          if (result?.message?.includes('already setup') || result?.code === 400) {
            const owner = db().prepare("SELECT id FROM \"user\" WHERE roleSlug = 'global:owner' LIMIT 1").get();
            if (!owner) throw new Error(`Setup failed: ${JSON.stringify(result)}`);
            id = owner.id;
          } else {
            throw new Error(`Setup failed: ${JSON.stringify(result)}`);
          }
        }

        // Also persist instanceUrl in SQLite — covers domain-change re-installs
        // where the setup endpoint returns 400 and skips the Host-based update
        db().prepare(
          "INSERT OR REPLACE INTO settings (key, value, loadOnStartup) VALUES ('instanceUrl', ?, 1)"
        ).run(JSON.stringify(url));

        console.log(JSON.stringify({ id }));
        break;
      }

      case 'users:list': {
        // Read directly from SQLite — simpler and avoids API pagination variance
        const users = db().prepare(
          'SELECT id, email, roleSlug FROM "user" WHERE disabled = 0'
        ).all();
        console.log(JSON.stringify(users.map(u => ({
          id: u.id,
          username: u.email,
          email: u.email,
          role: u.roleSlug,
        }))));
        break;
      }

      case 'users:add': { // <login> <email> <password> <role>
        const [, email, password, role] = args;
        if (!email || !password || !role) {
          throw new Error('Usage: users:add <login> <email> <password> <role>');
        }
        const validRoles = ['global:owner', 'global:admin', 'global:member'];
        if (!validRoles.includes(role)) {
          throw new Error(`Invalid role '${role}'. Valid roles: ${validRoles.join(', ')}`);
        }
        const existing = db().prepare('SELECT id FROM "user" WHERE email = ?').get(email);
        if (existing) throw new Error(`User already exists: ${email}`);
        const hashed = await bcryptjs.hash(password, 10);
        const id = crypto.randomUUID();
        const firstName = email.split('@')[0];
        const now = new Date().toISOString().replace('T', ' ').replace('Z', '');
        db().prepare(
          'INSERT INTO "user" (id, email, firstName, lastName, password, roleSlug, settings, disabled, mfaEnabled, createdAt, updatedAt)' +
          ' VALUES (?, ?, ?, ?, ?, ?, ?, 0, 0, ?, ?)'
        ).run(id, email, firstName, '', hashed, role, '{}', now, now);

        // n8n requires a personal project for every user
        const projectId = createHash('sha256').update(id).digest('base64url').slice(0, 16);
        const projectName = `${firstName} <${email}>`;
        db().prepare(
          'INSERT INTO project (id, name, type, createdAt, updatedAt, creatorId) VALUES (?, ?, ?, ?, ?, ?)'
        ).run(projectId, projectName, 'personal', now, now, id);
        db().prepare(
          'INSERT INTO project_relation (projectId, userId, role, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?)'
        ).run(projectId, id, 'project:personalOwner', now, now);

        console.log(JSON.stringify({ id }));
        break;
      }

      case 'users:delete': { // <userId>
        const [userId] = args;
        if (!userId) throw new Error('Usage: users:delete <userId>');
        const user = db().prepare('SELECT id, roleSlug FROM "user" WHERE id = ?').get(userId);
        if (!user) throw new Error(`User not found: ${userId}`);
        if (user.roleSlug === 'global:owner') throw new Error('Cannot delete the owner account');
        db().prepare('DELETE FROM "user" WHERE id = ?').run(userId);
        console.log(JSON.stringify({ success: true }));
        break;
      }

      case 'users:reset-password': { // <userId> <newPassword>
        const [userId, newPassword] = args;
        if (!userId || !newPassword) throw new Error('Usage: users:reset-password <userId> <newPassword>');
        const hashed = await bcryptjs.hash(newPassword, 10);
        const changes = db().prepare('UPDATE "user" SET password = ? WHERE id = ?').run(hashed, userId).changes;
        if (changes === 0) throw new Error(`User not found: ${userId}`);
        console.log(JSON.stringify({ success: true }));
        break;
      }

      case 'users:sso': { // <userId>
        const [userId] = args;
        if (!userId) throw new Error('Usage: users:sso <userId>');
        const user = db().prepare('SELECT id, email, password FROM "user" WHERE id = ?').get(userId);
        if (!user) throw new Error(`User not found: ${userId}`);
        const token = mintJwt(user.id, user.email, user.password);
        console.log(JSON.stringify({ cookie: 'n8n-auth', value: token, redirect: '/' }));
        break;
      }

      default:
        throw new Error(`Unknown command: ${command}`);
    }
  } catch (err) {
    process.stderr.write(JSON.stringify({ error: err.message }) + '\n');
    process.exit(1);
  }
})();
