<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Domains;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('ssl_cert_request')]
#[Description(<<<'MARKDOWN'
    Request a Let's Encrypt certificate for a domain

    Obtains a certificate for the domain from an ACME authority over HTTP-01 and installs it, then re-renders the vhost so the site serves it. The challenge is served by the running webserver, so nothing goes offline. The name must already resolve to this host. Use install-ssl-cert instead when you already hold a certificate.

    Calls POST /api/projects/{username}/domains/{domain}/request-ssl-cert. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class SslCertRequestTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/domains/{domain}/request-ssl-cert';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
            'domain',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'staging',
            'dry_run',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'domain' => $schema->string()->required(),
            'staging' => $schema->boolean()->description('Use Let\'s Encrypt\'s staging authority: the certificate is untrusted by browsers but spends no production rate limit. For rehearsing a request.'),
            'dry_run' => $schema->boolean()->description('Report what would be requested and why it would or would not work, without contacting the authority.'),
        ];
    }
}
