server {
    server_name  {{ $domain }};
    access_log /opt/panelalpha/shared-hosting/nginx-proxy-logs/{{ $domain }}/access.log combined;
    access_log /opt/panelalpha/shared-hosting/nginx-proxy-logs/{{ $domain }}/bytes.log bytes;
    error_log /opt/panelalpha/shared-hosting/nginx-proxy-logs/{{ $domain }}/error.log error;
    location / {
        @if (!empty($redirect_url))
            return 301 {{ $redirect_url }};
        @elseif (!empty($force_https_redirect))
            return 301 https://$host$request_uri;
        @else
            resolver 127.0.0.11;
            proxy_set_header Host {{ $domain }};
            proxy_set_header X-Real-IP $remote_addr;
            set $userhost {{ $user }};
            proxy_pass http://$userhost;
        @endif
    }
    location /phpmyadmin {
        proxy_set_header X-Real-IP $remote_addr;
        set $pmapass 0;
        if ($arg_pmassotoken) {
            set $pmapass 1;
        }
        if ($cookie_PMASignonSession) {
            set $pmapass 1;
        }
        if ($pmapass) {
            rewrite ^([^.]*[^/])$ $1/ permanent;
            rewrite ^/phpmyadmin(.*) /$1 break; 
            proxy_pass http://phpmyadmin-users.shared-hosting.palocal;
        }
    }
}
@if (!empty($ssl_enabled))
    server {
        listen 443 ssl;
        http2 on;
        server_name  {{ $domain }};
        ssl_certificate {{ $ssl_cert_pem_file }};
        ssl_certificate_key {{ $ssl_cert_key_file }};
        access_log /opt/panelalpha/shared-hosting/nginx-proxy-logs/{{ $domain }}/access.log combined;
        access_log /opt/panelalpha/shared-hosting/nginx-proxy-logs/{{ $domain }}/bytes.log bytes;
        error_log /opt/panelalpha/shared-hosting/nginx-proxy-logs/{{ $domain }}/error.log error;
        location / {
            @if (!empty($redirect_url))
                return 301 {{ $redirect_url }};
            @else
                resolver 127.0.0.11;
                proxy_set_header Host {{ $domain }};
                proxy_set_header X-Real-IP $remote_addr;
                set $userhost {{ $user }};
                proxy_pass https://$userhost;
            @endif
        }
        location /phpmyadmin {
            proxy_set_header X-Real-IP $remote_addr;
            set $pmapass 0;
            if ($arg_pmassotoken) {
                set $pmapass 1;
            }
            if ($cookie_PMASignonSession) {
                set $pmapass 1;
            }
            if ($pmapass) {
                rewrite ^([^.]*[^/])$ $1/ permanent;
                rewrite ^/phpmyadmin(.*) /$1 break; 
                proxy_pass http://phpmyadmin-users.shared-hosting.palocal;
            }
        }
    }
@endif