<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Git;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsDestructive;

#[Name('git_pull')]
#[Description(<<<'MARKDOWN'
    Pull from the git remote

    Pull from the git remote. Optional `path` defaults to `project` on DinD and `public_html` on FPM/LiteSpeed. Body `strategy` is `ff` (default; 422 if dirty), `force` (`reset --hard` origin/<branch> plus clean -fd), or `push_first`. Returns 422 when managed_by is deploy — use `project_rebuild`. Confirm with the operator before `force`.

    Calls POST /api/projects/{username}/git/pull. This changes server state.
    MARKDOWN)]
#[IsDestructive]
class GitPullTool extends ApiTool
{
    protected function method(): string
    {
        return 'POST';
    }

    protected function path(): string
    {
        return '/projects/{username}/git/pull';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function bodyParams(): array
    {
        return [
            'path',
            'strategy',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'path' => $schema->string()->description('Optional. Defaults to `project` (DinD) or `public_html` (FPM/LiteSpeed).'),
            'strategy' => $schema->string()->description('One of: ff, force, push_first.'),
        ];
    }
}
