<?php

// Generated by `php artisan mcp:tool:generate` from the OpenAPI
// document. Do not edit by hand -- change the #[OA\...] attributes on
// the controller and regenerate.

namespace App\Mcp\Tools\Api\Deploy;

use App\Mcp\Tools\Api\ApiTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

#[Name('project_inspect')]
#[Description(<<<'MARKDOWN'
    Inspect a project's deployed application files

    Reports what the project's files are - stack, ports, backing services, the commands a deploy would run - alongside the snapshot the last deploy froze onto the account, and lists where the two disagree. Reads /home/<username>/project by default (the main domain's document root for the classic PHP templates); `subdirectory` selects another directory under the account home. Values from .env files are never returned - only the variable names. This is POST /source/inspect with `type: project`, addressed by username: same report, same field names, and readable with a GET. The older spellings - the `/source-inspection` path and the `path` parameter - still work and are deprecated.

    Calls GET /api/projects/{username}/inspect.
    MARKDOWN)]
#[IsReadOnly]
#[IsIdempotent]
class ProjectInspectTool extends ApiTool
{
    protected function method(): string
    {
        return 'GET';
    }

    protected function path(): string
    {
        return '/projects/{username}/inspect';
    }

    /**
     * @return array<int, string>
     */
    protected function pathParams(): array
    {
        return [
            'username',
        ];
    }

    /**
     * @return array<int, string>
     */
    protected function queryParams(): array
    {
        return [
            'subdirectory',
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function argumentNames(): array
    {
        return [
            'name' => 'username',
        ];
    }

    /**
     * @return array<string, \Illuminate\JsonSchema\Types\Type>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'name' => $schema->string()->description('Name of the project. Sent to the API as `username`.')->required(),
            'subdirectory' => $schema->string()->description('Directory under the account home to inspect, e.g. "project", "public_html" or "project/apps/api". Absolute paths are accepted when they are inside the home directory. Named as it is on POST /source/inspect; `path` is accepted as a deprecated alias.'),
        ];
    }
}
